name: Test Build

on: 
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Run tests
        run: dotnet test
